### ISSUE TITLE
Logo preview

### ISSUE THREAD

**Issue by DunkleMango** [DunkleMango/StarboundModManager#11]
What do you think about this logo?
I created it today and wanted to hear your opinion.

Trying to put the functionality to form, I chose different symbols to represent each aspect.
A star in the middle (and some in the background) for "Starbound" and some gears for "mods".

Please tell me, if you think that we should include or change something here.

![main](https://user-images.githubusercontent.com/44678770/63055515-53407700-bee6-11e9-81ab-e57246253634.png)

**Comment by AbsolofDarkness** [comment]
That looks nice! Better than I could probably do. Makes sense you didn't use the Starbound logo due to copyright stuff. And it certainly stands out among other icons.

**Comment by DunkleMango** [comment]
Thank you for the praise! 😊
Yeah, I did want to find a way around copyright, and that was my best shot! :)
