### ISSUE TITLE
Search function for mods

### ISSUE THREAD

**Issue by DunkleMango** [DunkleMango/StarboundModManager#14]
**Is your feature request related to a problem? Please describe.**
When having many different mods, it will be easier to find what you are looking for in your long list of mods.

**Describe the solution you'd like**
A search bar for the mods that filters the mods that are shown.

**Describe alternatives you've considered**
Scrolling is NOT a good alternative! 😂

**Comment by AbsolofDarkness** [comment]
Making an issue to yourself to make sure you remember to implement it... nice to know I'm not the only one who does it :P

**Comment by DunkleMango** [comment]
When I have periods where I only work on university stuff, I might forget about it. Since I got a little bit of time on my hands now, I will try to push to get the next version ready. 😄

**Comment by DunkleMango** [comment]
Implemented in branch [appRework](https://github.com/DunkleMango/StarboundModManager/tree/appRework)
